
from .txt2any import CLASS_MAPPINGS as T2AMapping, CLASS_NAMES as T2ANames


NODE_CLASS_MAPPINGS = {
}
NODE_CLASS_MAPPINGS.update(T2AMapping)

NODE_DISPLAY_NAME_MAPPINGS = {

}
NODE_DISPLAY_NAME_MAPPINGS.update(T2ANames)
